name: Upload Apk
on: workflow_dispatch
jobs:
  build:
    name: Build Release Apk 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Running gradle assembleRelease
      run: gradle assembleDebug

    - name: Uploading Apk and Files
      uses: actions/upload-artifact@v2
      with:
        name: userland
        path: |
            app/build/outputs/apk/debug
            app/build/generated
      
    
